name: Build

on:
  workflow_dispatch:
    inputs:
      environments:
        description: 'Do you want to build  DEV, QA or Prod?'
          required: true
          type: choice
          default: "dev"
          options:
            - "dev"
            - "qa"
            - "prod"

env:
  HOME: /root
  SPACES_CLI_CICD: true
  SPACES_SOLUTION_ROLE: cicd-runner-admin
  SPACES_SOLUTION_ENV: ${{ github.event.inputs.environment }}

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build App
        id: buildApp
        run: |
          cd ./source
         
          cd ../
      - name: Install Build Agent SSH Key
        uses: niaid/monarch-actions-key-writer@v2
        with:
          key: ${{ secrets.NIAID_BUILD_AGENTS_SSH_KEY }}
          known_hosts: ${{ secrets.NIAID_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Export PATH
        id: spaces-path
        run: echo "$PATH:/root/.spaces-cli/bin" >> $GITHUB_PATH

      - name: Update Spaces CLI
        id: spaces-cli-update
        run: spaces update -stable

      - name: Build
        run: - spaces build image -file {{.SPACES_SOLUTION_FILE}} -tag {{.DOCKER_IMAGE_TAG}} -promote-to {{.SPACES_SOLUTION_ENV}}
